# Generated by Django 6.0.6 on 2026-06-12 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_member_count_community_post_count_and_more'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('image', 'Image')], db_index=True, default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', 'created_at'], name='posts_comme_post_id_976f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at'], name='posts_post_communi_ddf459_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-score', '-created_at'], name='posts_post_score_144121_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['post', 'value'], name='posts_vote_post_id_88eb32_idx'),
        ),
    ]
