# Generated by Django 6.0.6 on 2026-06-12 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=110, unique=True),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-member_count'], name='communities_member__b80a75_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-post_count'], name='communities_post_co_3d816f_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['community', 'is_active', 'role'], name='communities_communi_fe61c9_idx'),
        ),
    ]
