from django.contrib import admin
from .models import Community, Membership


@admin.register(Community)
class CommunityAdmin(admin.ModelAdmin):
    list_display = ('name', 'slug', 'member_count', 'post_count', 'is_private', 'created_by', 'created_at')
    list_filter = ('is_private',)
    search_fields = ('name', 'description')
    readonly_fields = ('slug', 'member_count', 'post_count', 'created_at', 'updated_at')
    prepopulated_fields = {}  # slug auto-generated by model


@admin.register(Membership)
class MembershipAdmin(admin.ModelAdmin):
    list_display = ('user', 'community', 'role', 'is_active', 'joined_at')
    list_filter = ('role', 'is_active')
    search_fields = ('user__username', 'community__name')
    raw_id_fields = ('user', 'community')
