import logging
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db import transaction
from .models import Community, Membership
from .forms import CommunityCreateForm

logger = logging.getLogger('canopy')

PAGE_SIZE = 20


def community_list_view(request):
    qs = Community.objects.order_by('-member_count')
    paginator = Paginator(qs, PAGE_SIZE)
    page = paginator.get_page(request.GET.get('page'))
    return render(request, 'communities/list.html', {'page_obj': page})


def community_detail_view(request, slug):
    community = get_object_or_404(Community, slug=slug)
    posts_qs = community.posts.select_related('author').order_by('-is_pinned', '-created_at')
    paginator = Paginator(posts_qs, PAGE_SIZE)
    page = paginator.get_page(request.GET.get('page'))

    is_member = False
    user_role = None
    if request.user.is_authenticated:
        membership = Membership.objects.filter(
            user=request.user, community=community, is_active=True
        ).first()
        if membership:
            is_member = True
            user_role = membership.role

    return render(request, 'communities/detail.html', {
        'community': community,
        'page_obj': page,
        'is_member': is_member,
        'user_role': user_role,
    })


@login_required
def community_create_view(request):
    if request.method == 'POST':
        form = CommunityCreateForm(request.POST, request.FILES)
        if form.is_valid():
            with transaction.atomic():
                community = form.save(commit=False)
                community.created_by = request.user
                # slug generated by model.save()
                community.save()
                Membership.objects.create(
                    user=request.user, community=community, role='admin'
                )
                community.recalc_member_count()
            logger.info("Community created: %s by %s", community.name, request.user.username)
            messages.success(request, f"Community c/{community.name} created!")
            return redirect('communities:detail', slug=community.slug)
    else:
        form = CommunityCreateForm()
    return render(request, 'communities/create.html', {'form': form})


@login_required
@require_POST
def join_community_view(request, slug):
    community = get_object_or_404(Community, slug=slug)
    with transaction.atomic():
        membership, created = Membership.objects.get_or_create(
            user=request.user, community=community,
            defaults={'is_active': True}
        )
        if not created:
            membership.is_active = not membership.is_active
            membership.save()
            action = 'joined' if membership.is_active else 'left'
        else:
            action = 'joined'
        community.recalc_member_count()
    messages.success(request, f"You have {action} c/{community.name}")
    return redirect('communities:detail', slug=community.slug)


def _check_mod_permission(user, community):
    """Return True if user is mod/admin of community or site staff."""
    if user.is_staff:
        return True
    return Membership.objects.filter(
        user=user, community=community,
        role__in=['moderator', 'admin'], is_active=True
    ).exists()
