# Generated by Django 6.0.6 on 2026-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('communities', '0002_community_member_count_community_post_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-reputation'], name='accounts_us_reputat_d74670_idx'),
        ),
    ]
